// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABU2DtecIRM12i5e_h3F9_4xS83XEteVg',
    appId: '1:497144559839:web:8c88ef3af75feb3780116a',
    messagingSenderId: '497144559839',
    projectId: 'powervortex-1',
    authDomain: 'powervortex-1.firebaseapp.com',
    databaseURL: 'https://powervortex-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powervortex-1.appspot.com',
    measurementId: 'G-KHSBPB6DK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQOIr_buWAHCDAJYuTMjpZCn-7eb-vUY',
    appId: '1:497144559839:android:863a436af7e9a02280116a',
    messagingSenderId: '497144559839',
    projectId: 'powervortex-1',
    databaseURL: 'https://powervortex-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powervortex-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZB0RZ-2f5IFsCjMOqfnd5sbCEDG4qlA',
    appId: '1:497144559839:ios:3a00db63b8375d7780116a',
    messagingSenderId: '497144559839',
    projectId: 'powervortex-1',
    databaseURL: 'https://powervortex-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powervortex-1.appspot.com',
    iosClientId: '497144559839-1qcdct93de8du01oprgtuu45f50a8kup.apps.googleusercontent.com',
    iosBundleId: 'com.example.powervortex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYZB0RZ-2f5IFsCjMOqfnd5sbCEDG4qlA',
    appId: '1:497144559839:ios:68b7d2740eebce2480116a',
    messagingSenderId: '497144559839',
    projectId: 'powervortex-1',
    databaseURL: 'https://powervortex-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powervortex-1.appspot.com',
    iosClientId: '497144559839-1jb9loq6mtj770ab4hflksu9ej5kfan1.apps.googleusercontent.com',
    iosBundleId: 'com.example.powervortex.RunnerTests',
  );
}
